### PR TITLE
MidoNet Enterprise Insights

### PR DESCRIPTION
**Pull request by ryo-tagami**
Add MidoNet Enterprise Insights feature to MidoNet Agent.

Signed-off-by: Ryo Tagami <rtagami@airstrip.jp>

### CODE REVIEW

**Comment by abelboldu** [comment]
Is lldpd a requirement? If so, we should add it to our repos.

**Comment by ryo-tagami** [comment]
Apparently so, it's in the Insights Documentation:
http://docs.midokura.com/docs/latest-en/insights-guide/content/prerequisites.html
> On RHEL. Follow the instructions on http://software.opensuse.org/download.html?project=home:vbernat&package=lldpd to set-up the required repositories (under the RHEL tab).  For RHEL7 the commands are:
```
# cd /etc/yum.repos.d/
# wget http://download.opensuse.org/repositories/home:vbernat/RHEL_7/home:vbernat.repo
```
> Then the package can be installed via:
```
# yum install lldpd
```
I'm happy to change it if we can have it in our repository.

**Comment by abelboldu** [comment]
No, just an observation. I'll create a jira for that.

Merging

**Comment by ryo-tagami** [comment]
Oh, OK, cool. Once we have `lldpd` in our repository, we can stop adding OpenSUSE repository.

**Pull request merged**
